### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by mlocati** [zendframework/zend-http#104]
...no updates for months...

**Comment by Ocramius** [comment]
> ...no updates for months...

Doesn't mean dead :-)

Most libraries nowadays rely on the [PSR-7](http://www.php-fig.org/psr/psr-7/) standard, so there is no interest/traction in adding features to this API. [zend-diactoros](https://github.com/zendframework/zend-diactoros) is our own PSR-7 implementation.

**Comment by mlocati** [comment]
I consider a project with unanswered pull requests and issues a dead project...

**Comment by Ocramius** [comment]
@mlocati be my guest in answering issues and pull request from 4 years ago on many of my (personal stuff, not just zf) actively maintained projects :-)

**Comment by mlocati** [comment]
That means that you don't have time to give feedback to requests to zend-http?

**Comment by Ocramius** [comment]
Yes, and I generally answer things as they come up in my inbox.
If I skip something, it's just because I wasn't working on it at that time,
and then it gets archived when I clean up my inbox.
Also, most contributors only work on this when they have free time, at the
end of the day or before going to work.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/
